language: python
python: 3.3

env:
  - TOXENV=graphite-api
  - TOXENV=graphite-web
  - TOXENV=lint

before_install:
  - sudo apt-get -y install libcairo2-dev

install:
  - pip install tox

script:
  - tox -e $TOXENV
